COLOR_RED = "red"
COLOR_YELLOW = "yellow"
COLOR_BLUE = "blue"
COLOR_GREEN = "green"
COLOR_PURPLE = "purple"
COLOR_ORANGE = "orange"
COLOR_VERMILION = "vermilion"
COLOR_AMBER = "amber"
COLOR_CHARTREUSE = "chartreuse"
COLOR_TEAL = "teal"
COLOR_VIOLET = "violet"
COLOR_MAGENTA = "magenta"

MATCH = "match"
COMPLEMENT = "complement"